### ISSUE TITLE
Failed to install addin 'Cake.Hosts'

### ISSUE THREAD

**Issue by olsh** [AMVSoftware/Cake.Hosts#12]
I get the following error when trying to install `Cake.Hosts` with `#addin "Cake.Hosts"` command

```
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Hosts'.                                                                                                                   
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 106
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152         
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41                                                             
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45                                                                             
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 73                                                                                                               
```

But the installation works with the previous version
`#addin "nuget:?package=Cake.Hosts&version=1.2.1"`

Tried with `dontet cake` global tool and with the classic `build.ps1` script.
Cake version is 0.30

**Comment by trailmax** [comment]
I suspect this is Cake version mismatch. This addon is currently on v0.29.0. 
Just out of interest, if you change your Cake version to v0.29.0 does it load?

**Comment by trailmax** [comment]
@olsh Just pushed new version of Cake.Hosts that works with latest version of Cake v0.30.0. Give it a go please

**Comment by olsh** [comment]
Hi @trailmax,
Thanks for the response.

Sadly, but this didn't help, the same issue.

```
Processing build script...                                                                                      
Installing addins...                                                                                            
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/cake.hosts/index.json                                 
Found package 'Cake.Hosts 1.4.0' in 'C:/Projects/my-project/tools/Addins'.                               
Package Cake.Hosts.1.4.0 has already been installed.                                                            
Successfully installed 'Cake.Hosts 1.4.0' to C:/Projects/my-project/tools/Addins                         
Executing nuget actions took 37.85 ms                                                                           
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Hosts'.                                           
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)      
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)                                                   
   at Cake.CakeApplication.Run(CakeOptions options)                                                             
   at Cake.Program.Main()                                                                                       
```

The installation also fails with Cake 0.29.0.

My thoughts that it can be target framework update, 1.2.1 is targeted to full .NET Framework.

**Comment by trailmax** [comment]
Any chance of a script with a reproduction of the issue?

Max

**Comment by olsh** [comment]
I can reproduce the issue with the one-liner
`#addin "Cake.Hosts"`

**Comment by trailmax** [comment]
@olsh yeah.. indeed. I see the problem started when I've started only targeting netstandard 2.0. I'll see what can be done about this

**Comment by trailmax** [comment]
@olsh  Just pushed another release https://www.nuget.org/packages/Cake.Hosts/1.4.1 with restored build for `.net461` - that was removed before with the hope that pure netstandeard is supported.

Can you give it another try please?

**Comment by olsh** [comment]
It works now, thank you!
I think we can close the issue.

**Comment by trailmax** [comment]
Good stuff! glad it works now!
